### ISSUE TITLE
Move translations to a GMS platform (e.g. Transifex)

### ISSUE THREAD

**Issue by vorotnikov** [XQF/xqf#107]
Forcing volunteers to study mostly Linux-only tools (e.g. Poedit) and open Pull Requests for every edit of translation is just not cool. Also updating .po files after every single template change is pain.

A platform like Transifex or Launchpad will help us crowdsource translations from concerned citizens without technical skills. Maintaining existing ones will become easier too.

**Comment by illwieckz** [comment]
Hi. It's a good idea, I don't know how works Transifex and how to link Transifex to po files in this repository. I cannot promise anything but I'll look into this. :-)

**Comment by vorotnikov** [comment]
I could set up XQF Transifex project but the github import bot is up to you.

**Comment by illwieckz** [comment]
see #112, it works, thanks to @vorotnikov for his precious help.
