### ISSUE TITLE
Port to GTK+ 3

### ISSUE THREAD

**Issue by skybon** [XQF/xqf#114]
The process is described at https://developer.gnome.org/gtk3/stable/gtk-migrating-2-to-3.html

Depends on: #92

**Comment by illwieckz** [comment]
Yes, there is already the issue #14 **Port XQF to GTK+3** and before that #13 **Fix XQF to have an undeprecated and clean GTK+2 version**. :stuck_out_tongue: 

So I merge your issue with the #14 one :smile:
