### ISSUE TITLE
Create an english language translation file to allow UTF-8 characters

### ISSUE THREAD

**Issue by illwieckz** [XQF/xqf#122]
With `LANG=C` we can't use UTF-8 characters like ©, but we can create an english po file to have them (replacing ASCII `(C)` by UTF-8 `©`).

**Comment by jmallach** [comment]
I object to this. I don't see the point, other than the usual en_GB, en_CA etc translations to change a few words like "color" → "colour", etc.

All modern systems should be assumed to be running on a UTF-8 locale, and I would actually force that in the code, if it's not done already.

Debian even has a C.UTF-8 locale.

**Comment by illwieckz** [comment]
OK.

**Comment by illwieckz** [comment]
For the `©` example, it means replacing this string in the code will affect all translations.
