### ISSUE TITLE
Kill Autotools with fire

### ISSUE THREAD

**Issue by skybon** [XQF/xqf#138]
Autotools, current build system, is painful to use.
- Build chain is very complex. [One image that says it all](http://www.shlomifish.org/lecture/Autotools/slides/processing-diagram.png). Right now we have a pile of .am, .in and .ac files in every folder. Seriously?
- Config files have some really horrid syntax. Passages like this:
```
dnl Use -Wall if we have gcc.
changequote(,)dnl
if test "x$GCC" = "xyes"; then
  case " $CFLAGS " in
  *[\ \	]-Wall[\ \	]*) ;;
  *) CFLAGS="$CFLAGS -Wall" ;;
  esac
fi
changequote([,])dnl
```
are way too much black woodoo shell magic for a build configuration.
- They are very verbose. [Compare:](https://github.com/skandhurkat/Just-For-Fun/tree/bdde18af6cf5133a8f5812b2743c198db581db33/Library) a crapload of AM/AC/IN and a small, concise CMakeLists.txt
- Autotools is *not* forward-compatible. What compiles today might not compile in a year because autotools tends to break old applications and libraries.

Autotools has been nicknamed *autohell* for these reasons. It has to go.

There are many modern alternatives out there. Let's take CMake for example.

CMake is an open source build system published under a BSD-style license. It generates native makefiles and workspaces that can be used in the compiler environment of developer's choice. It is currently used by KDE and MySQL among others.

From my experience CMake is very easy to master, works blazing fast and even has very shiny output.

Currently I estimate that 2 CMake listfiles (CMakeLists.txt) and 1 .in is enough to build xqf executable. Compare that to >30 files with a large .gitignore.

Therefore I propose CMake as the new XQF build system.

**Comment by illwieckz** [comment]
I'm not against a port to CMake.
