### ISSUE TITLE
Quake 3 memory settings issues

### ISSUE THREAD

**Issue by zturtleman** [XQF/xqf#139]
* Memory settings are saved in XQF config for all Quake 3 based games, but only displayed for Quake 3.
  * Hunk megs defaults to 54, but the "default" button sets hunk megs to 56.
  * Sound megs defaults to 8 MB, but GUI has a minimum of 16 MB.
  * XQF requires zone megs + sound megs to be less than hunk megs, but there is no technical reason for this.
  * The cg_precachedModels setting is not mega bytes and is only used by the Art of War mod. It appears XQF used the [Art of War FAQ](http://www.quakewiki.net/archives/artofwar/faq.html) as a basis for the memory presets.

**Comment by zturtleman** [comment]
The issues are fixed in the following commits;

d2421e2 Only save memory settings for Quake 3
c2c930d Fix Quake 3 memory settings default com_hunkMegs value
7bc7bc4 Allow Quake 3 memory settings to use 8 sound megs
b78caac Don't check if Quake 3 zone/sound megs fit in hunk
fff29e8 Remove cg_precachedModels from Quake 3 memory settings

**Comment by illwieckz** [comment]
Woaw, thanks a lot ! :+1:
