### ISSUE TITLE
Add WON2 (Half-Life old) Master Server

### ISSUE THREAD

**Issue by Xylemon** [XQF/xqf#154]
This is the last working third party Master Server for Half-Life's WON (or original CD version protocol): 

master://master3.won2.steamlessproject.nl:27010 - WON2 Masterserver #3 (USA, Transistor62)

Would be great if it could be added to XQF. Another project will come out called NeuWON soon and I suppose I'll post that master server when it releases.

**Comment by illwieckz** [comment]
This master server seems to work in XQF but is very sloooow to update. o.O

**Comment by illwieckz** [comment]
Thanks for this master server, feel free to share all master servers you know for games supported by XQF. :wink:

**Comment by Xylemon** [comment]
That reminds me, it might be a good idea to investigate the Steam Master Servers again. Last time I looked into it, the problem seemed to be that the Master server wasn't split up per game, but rather a giant list for all Steamworks game. Some more info here: https://developer.valvesoftware.com/wiki/Master_Server_Query_Protocol
