### ISSUE TITLE
msgfmt: unrecognized option '--desktop'

### ISSUE THREAD

**Issue by zturtleman** [XQF/xqf#167]
Attempting to compile using the new cmake build system on Debian Wheezy gives an error

    msgfmt: unrecognized option '--desktop'

**Comment by skybon** [comment]
You need gettext 0.19 and higher to build translations.

**Comment by illwieckz** [comment]
* wheezy-backports distributes 0.19
* jessie distributes 0.19
* next xqf release will be distributed by stretch

So:
* people can build xqf with gettext on wheezy (old stable)
* people can build xqf with gettext on jessie (stable)
* Debian can build xqf with gettext on stretch (next stable)

I think we can close this issue.

@zturtleman: you will need wheezy-backports for `libminizip-dev` too.

**Comment by zturtleman** [comment]
Okay, thanks for the help.
