### ISSUE TITLE
Do not rebuild things at install time

### ISSUE THREAD

**Issue by illwieckz** [XQF/xqf#180]
All this files are created both at `make` stage and `make install` stage, it's not needed at all at `make install` stage and it fools installation tracking tools:

```
build/games.c
build/ca.gmo
build/ca.po
build/CMakeFiles
build/da.gmo
build/da.po
build/de.gmo
build/de.po
build/es.gmo
build/es.po
build/fi.gmo
build/fi.po
build/fr.gmo
build/fr.po
build/LINGUAS
build/pl.gmo
build/pl.po
build/ru.gmo
build/ru.po
build/xqf.desktop
```

This issue was introduced when the build process was ported to cmake. @skybon have you an idea to fix that?

**Comment by skybon** [comment]
@illwieckz Unfortunately, I am not working on XQF source code anymore. I believe that the current codebase is hopelessly rotten and rewriting from scratch in a better language would be a better solution for everyone involved.

Therefore all my efforts are currently on the next gen [Obozrenie Game Server Browser](https://github.com/obozrenie/obozrenie). It's written in Python and designed to be modular from day 1.

**Comment by illwieckz** [comment]
people can just use the `CMAKE_SKIP_INSTALL_ALL_DEPENDENCY` option to not build at install time, this way:

```
cmake .. -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=1
make
make install
```

This option ensures the `install` target does not build anything, so tracking software like `checkinstall` are not fooled by build temporary files. Of course it means `make` _must_ be called first and have succeeded.

For `checkinstall` users a ready-to-use helper exists named `tools/do_checkinstall`.
