### ISSUE TITLE
do not play sound if selected sound is… a directory

### ISSUE THREAD

**Issue by illwieckz** [XQF/xqf#183]
Do not play sound is selected sound is… a directory

**Comment by illwieckz** [comment]
For example if the selected player is `mpv`, it will read recursively thousands of directory, filling your whole memory in seconds! :fearful:

**Comment by zturtleman** [comment]
Unset sounds falling back to current working directory is fix in 30506664b4cf18a99c1a9fc26987607da76159be. It's not possible to choose a directory either.

I'm not sure if it's necessary to check if the sound is a directory as this issue was introduced after the last release (#143). Thoughts?

**Comment by illwieckz** [comment]
> I'm not sure if it's necessary to check if the sound is a directory as this issue was introduced after the last release (#143). Thoughts?

It's ok to not take care too much of this kind of stuff, and people can fix it very easily (just clicking the reset button near the file entry). Thanks for the fix !
