### ISSUE TITLE
What is “skin” and what is the purpose of skin.c and skin_pcx.c ?

### ISSUE THREAD

**Issue by illwieckz** [XQF/xqf#39]
What is “skin” and what is the purpose of ``skin.c`` and ``skin_pcx.c`` ?

**Comment by Xylemon** [comment]
What @zturtleman said is exactly right. PCX is the image format Quake used for its textures. In Quake, players had the ability to change the textures of their playermodel (or skin) and everyone would be able to see it. XQF has a nice way of allowing you to do with the individual game configuration menu.

**Comment by illwieckz** [comment]
OK, thanks. :-).
