### ISSUE TITLE
Delete xqf.spec

### ISSUE THREAD

**Issue by illwieckz** [XQF/xqf#50]
fix xqf.spec to be able to use checkinstall under Debian/Ubuntu

**Comment by illwieckz** [comment]
…or delete the `xqf.spec`.
@lnussel , do you need it for suse packaging ? I think the better place for this kind of package-related stuff is on the distro-side.

**Comment by lnussel** [comment]
the spec file in the repo is outdated, obs has the master copy. feel free to remove

**Comment by illwieckz** [comment]
Thanks.

**Comment by lnussel** [comment]
The package is here btw, it builds automatically on every github commit
https://build.opensuse.org/package/show/games:tools/xqf

it could automatically build for other distros as well if someone bothers to modify the spec file

**Comment by illwieckz** [comment]
Nice, I'm looking for building packages for Debian and Ubuntu.
(Arch users already have https://aur.archlinux.org/packages/xqf-git/ )
