### ISSUE TITLE
XQF does not compile trayicon stuff on Fedora 21/jhbuild

### ISSUE THREAD

**Issue by Obsidien** [XQF/xqf#88]
On a Fedora 21 and in jhbuild environment, I was able to compile only after removing/commenting the line:
```C
#include <gdk-pixbuf-xlib/gdk-pixbuf-xlib.h>
```
in the file src/trayicon.c. I have no idea what I’m doing!

**Comment by illwieckz** [comment]
Since it seems pretty specific, I close this issue. If someone needs it, feels free to reopen it.
