### ISSUE TITLE
Does we need the trayicon stuff?

### ISSUE THREAD

**Issue by illwieckz** [XQF/xqf#89]
Is it relevant to put manpower on it?

**Comment by skybon** [comment]
No, since XQF is not a tool meant to be run in background. We could in theory write a daemon-based web interface but that won't use a tray icon either.

**Comment by Xylemon** [comment]
I actually like the tray since I do run XQF in the background.

**Comment by illwieckz** [comment]
I’m so sorry @Xylemon, it appears we do not have enough manpower to maintain that. :confused:

Badly, the trayicon stuff is a very rusty and unmaintainable code that prevents us to update and maintain the whole code (with this stuff, we are stuck to GTK2 and X11 internals, and and it unnecessarily complicates the build process). It seems no active people have a better code to offer. So I will merge the @skybon pull request that remove the trayicon. :confused:

In fact, the only safe way to keep the trayicon is to drop the current code and rewrite another one with a modern dedicated API.

If you want to add a new code using a more modern and higher-level and maintainable API, feel free to submit a pull-request. :wink:

**Comment by illwieckz** [comment]
Obviously, it fixes that:

```
trayicon.c: In function ‘tray_init’:
trayicon.c:459:2: warning: implicit declaration of function ‘gdk_pixbuf_xlib_init’ [-Wimplicit-function-declaration]
  gdk_pixbuf_xlib_init (GDK_DISPLAY(), DefaultScreen (GDK_DISPLAY()));
  ^
trayicon.c: In function ‘kde_dock_background’:
trayicon.c:673:2: warning: implicit declaration of function ‘gdk_pixbuf_xlib_get_from_drawable’ [-Wimplicit-function-declaration]
  background=gdk_pixbuf_xlib_get_from_drawable (NULL, win, 0, NULL,
  ^
trayicon.c:673:12: warning: assignment makes pointer from integer without a cast
  background=gdk_pixbuf_xlib_get_from_drawable (NULL, win, 0, NULL,
```

**Comment by Yascor** [comment]
Damn, Im using XQF more than decade and tray icon was pretty much priority for me,  plus possibility to hide/minimize to there after game start (from other side I could just use web based server browsers). Was always good to have it in tray/background, just few clicks and could check my servers, rcon stuff etc, I dont like programs which using pretty often to flying somewhere in taskbar. I hope somebody will be abble to help with rewrite :)

ps Maybe at least setting "minimize after game start" ?

**Comment by skybon** [comment]
@Yascor Sounds like you are used to tray being icon-only taskbar2. If so, you are using tray wrong.

**Comment by Yascor** [comment]
@skybon Im sorry, Im just XFCE user and not many distros got some fancy taskbars/activators for it (in type of win7, gnome etc). I guess I will have to look around to compile one. Thank you for reminder. Fight with old habits isnt sometimes easy :)

**Comment by illwieckz** [comment]
@skybon wrotes:

> @Yascor Sounds like you are used to tray being icon-only taskbar2. If so, you are using tray wrong.

Please, never say to someone _“you are wrong”_ as welcome message. :scream:

@Yascor wrotes:
> Maybe at least setting "minimize after game start" ?

It could be a very good idea and since the trayicon is just a taskbar2 with another look on another place, a "minimize to traybar1" mechanic instead of "minimize to traybar2" can satisfy the user.

I don't have the time myself right now to see what can be done, but it's something that could be usefull to do.

The priority is to modernize the gui, perhaps it could be easier to do later when some old mechanism will be cleaned up. :wink:
