### ISSUE TITLE
Avoid individual GLib/GTK includes

### ISSUE THREAD

**Issue by jmallach** [XQF/xqf#92]
GTK/Glib deprecated stuff like `#include <glib/glib-i18n.h>` a while back. Modern GLib/GTK prefers just a single include with `<glib/glib.h>`, etc.

I'll post a patch to get rid of them.

**Comment by skybon** [comment]
I'm going to run through it and post a patch later today.

**Comment by illwieckz** [comment]
see 8c068f2 from @jmallach too.
